name: Build, Deploy Javadoc & Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

permissions:
  contents: write # Nécessaire pour publier sur gh-pages ET créer la release

jobs:
  publish-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' # Option requise pour les nouvelles versions de setup-java

      - name: Build Project (JAR)
        run: mvn clean package -DskipTests
        # Cette commande compile le projet et crée le fichier .jar dans le dossier "target/"

      - name: Generate Javadoc
        run: |
          mvn javadoc:javadoc
          mkdir -p agent/build/docs/javadoc
          cp -r target/site/apidocs/* agent/build/docs/javadoc

      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
          folder: agent/build/docs/javadoc
          target-folder: javadoc

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar
          generate_release_notes: true